In [1]:
import numpy as np

In [2]:
# Q1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [3]:
# Q2
print("Data types of elements in list_:")
for elem in list_:
    print(type(elem))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
print("\nData types of elements in array_list:")
for elem in array_list:
    print(type(elem))


Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [6]:
# Q3
array_list = np.array(object=list_, dtype=int)
print("Data types of elements in list_:")
for elem in list_:
    print(type(elem))

print("\nData types of elements in array_list after dtype=int:")
for elem in array_list:
    print(type(elem))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list after dtype=int:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [7]:
# Q4
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [8]:
# Q5
zeros_matrix = np.zeros((3, 3))
print("3x3 matrix of zeros:\n", zeros_matrix)

3x3 matrix of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Q6
identity_matrix = np.eye(5)
print("5x5 identity matrix:\n", identity_matrix)

5x5 identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
